### ISSUE TITLE
CTDing on AMD GPU (AMD Test build v1)

### ISSUE THREAD

**Issue by ioquirk** [GreenComfyTea/MHW-Better-Matchmaking#1]
The game instantly crashes to desktop on clicking confirm to matchmake/filter lobby list, with this AMD test version. Using on a 2022 ROG Zephyrus G14 model with an AMD Radeon RX 6800S dGPU. Sharp Loader 0.0.4.1 was installed.

> [ 01:38:42.1397685 | SPL ] [AddressRepo] Restored from address record cache.
> [ 01:38:42.1405607 | SPL ] [Preloader] Resolved address for __scrt_common_main_seh: 0x1427414F4
> [ 01:38:42.1405767 | SPL ] [Preloader] Resolved address for WinMain: 0x1413A4C00
> [ 01:38:42.1405841 | SPL ] [Preloader] Resolved address for sMhMain::ctor: 0x141AEBB00
> [ 01:38:42.1410200 | SPL ] [Preloader] Initializing CLR / NativePluginFramework
> [ 01:38:42.1653508 | SPL ] Loading bootstrapper from C:\Program Files (x86)\Steam\steamapps\common\Monster Hunter World\nativePC\plugins\CSharp\Loader\SharpPluginLoader.Bootstrapper.dll
> [ 01:38:42.1893685 | SPL ] [Bootstrapper] Initializing SharpPluginLoader.Core
> [ 01:38:42.2099364 | SPL ] [Bootstrapper] SharpPluginLoader.Core loaded
> [ 01:38:42.2104196 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.2694251 | SPL ] [Bootstrapper] Loading System.Collections
> [ 01:38:42.2698505 | SPL ] [Bootstrapper] Loading System.Runtime.InteropServices
> [ 01:38:42.2710571 | SPL ] [Core] Retrieved Function pointers
> [ 01:38:42.3134058 | SPL ] sMhMain::move: 0x141af1e90
> [ 01:38:42.3135771 | SPL ] Dialog Virtual Function [3] = 0x141ec9790
> [ 01:38:42.3135902 | SPL ] Dialog Virtual Function [4] = 0x1402405c0
> [ 01:38:42.3135972 | SPL ] Dialog Virtual Function [5] = 0x1402406b0
> [ 01:38:42.3136033 | SPL ] DisplayYesNoDialog = 0x141ae1380
> [ 01:38:42.3136470 | SPL ] [Bootstrapper] Loading System.Numerics.Vectors
> [ 01:38:42.3149151 | SPL ] [Bootstrapper] Loading System.Drawing.Primitives
> [ 01:38:42.3162220 | SPL ] [Core] Found method SharpPluginLoader.Core.SingletonManager.GetSingletonNative in cache
> [ 01:38:42.3172474 | SPL ] [Core] Uploading internal call QueueYesNoDialog
> [ 01:38:42.3175204 | SPL ] [Core] Uploading internal call LoadTexture
> [ 01:38:42.3175554 | SPL ] [Core] Uploading internal call UnloadTexture
> [ 01:38:42.3175682 | SPL ] [Core] Uploading internal call RegisterTexture
> [ 01:38:42.3175788 | SPL ] [Core] Uploading internal call LoadChunk
> [ 01:38:42.3175882 | SPL ] [Core] Uploading internal call GetDefaultChunk
> [ 01:38:42.3175972 | SPL ] [Core] Uploading internal call RequestChunk
> [ 01:38:42.3176056 | SPL ] [Core] Uploading internal call ChunkGetFile
> [ 01:38:42.3176143 | SPL ] [Core] Uploading internal call ChunkGetFolder
> [ 01:38:42.3176227 | SPL ] [Core] Uploading internal call FileGetContents
> [ 01:38:42.3176305 | SPL ] [Core] Uploading internal call FileGetSize
> [ 01:38:42.3176391 | SPL ] [Core] Uploading internal call BeginTimeline
> [ 01:38:42.3176520 | SPL ] [Core] Uploading internal call EndTimeline
> [ 01:38:42.3176613 | SPL ] [Core] Uploading internal call BeginTimelineGroup
> [ 01:38:42.3176703 | SPL ] [Core] Uploading internal call EndTimelineGroup
> [ 01:38:42.3176791 | SPL ] [Core] Uploading internal call TimelineTrack
> [ 01:38:42.3176885 | SPL ] [Core] Uploading internal call Bitfield
> [ 01:38:42.3176974 | SPL ] [Core] Uploading internal call NotificationSuccess
> [ 01:38:42.3177089 | SPL ] [Core] Uploading internal call NotificationError
> [ 01:38:42.3177184 | SPL ] [Core] Uploading internal call NotificationWarning
> [ 01:38:42.3177263 | SPL ] [Core] Uploading internal call NotificationInfo
> [ 01:38:42.3177365 | SPL ] [Core] Uploading internal call Notification
> [ 01:38:42.3177450 | SPL ] [Core] Uploading internal call RenderNotifications
> [ 01:38:42.3177530 | SPL ] [Core] Uploading internal call GetRepositoryAddress
> [ 01:38:42.3177612 | SPL ] [Core] Uploading internal call GetGameRevision
> [ 01:38:42.3258798 | SPL ] [Bootstrapper] Loading System.Text.Json
> [ 01:38:42.3274309 | SPL ] [Bootstrapper] Loading System.Collections.Concurrent
> [ 01:38:42.3747555 | SPL ] Game revision: 421652
> [ 01:38:42.3748078 | SPL ] [Core] Restoring from plugin record cache.
> [ 01:38:42.3771852 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3772815 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3775625 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3775795 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3776652 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3778184 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3780517 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3781163 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3782086 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3784233 | SPL ] [Bootstrapper] Loading Reloaded.Hooks
> [ 01:38:42.3793656 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.3794449 | SPL ] [Bootstrapper] Loading Reloaded.Hooks.Definitions
> [ 01:38:42.3958665 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.3975321 | SPL ] [Bootstrapper] Loading System.Runtime.InteropServices
> [ 01:38:42.3981697 | SPL ] [Bootstrapper] Loading Reloaded.Memory.Buffers
> [ 01:38:42.4001603 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.4011521 | SPL ] [Bootstrapper] Loading System.Linq
> [ 01:38:42.4023747 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.4027803 | SPL ] [Bootstrapper] Loading Reloaded.Assembler
> [ 01:38:42.4047383 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.4048645 | SPL ] [Bootstrapper] Loading System.Diagnostics.Process
> [ 01:38:42.4064075 | SPL ] [Bootstrapper] Loading System.Diagnostics.Process
> [ 01:38:42.4065868 | SPL ] [Bootstrapper] Loading System.Runtime.InteropServices
> [ 01:38:42.4068453 | SPL ] [Bootstrapper] Loading Reloaded.Memory
> [ 01:38:42.4086125 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.4087224 | SPL ] [Bootstrapper] Loading System.Diagnostics.Process
> [ 01:38:42.4089484 | SPL ] [Bootstrapper] Loading System.Threading
> [ 01:38:42.4090955 | SPL ] [Bootstrapper] Loading System.Collections.Concurrent
> [ 01:38:42.4119580 | SPL ] [Bootstrapper] Loading System.Collections
> [ 01:38:42.4127204 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4146171 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4150190 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4189357 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4315534 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4445205 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4452184 | SPL ] [Bootstrapper] Loading System.Linq
> [ 01:38:42.4532288 | SPL ] [Bootstrapper] Loading System.Diagnostics.Process
> [ 01:38:42.4534448 | SPL ] [Bootstrapper] Loading System.Runtime.CompilerServices.Unsafe
> [ 01:38:42.4550064 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550066 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550173 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550268 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550054 | SPL ] [ 01:38:42.4550090 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550057 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550126 | SPL ] [kernel32.dll] Resolved Path: 
> [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550150 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4550108 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.4583929 | SPL ] [Bootstrapper] Loading System.Runtime.InteropServices
> [ 01:38:42.4620792 | SPL ] [Bootstrapper] Loading System.Threading
> [ 01:38:42.4624667 | SPL ] [Bootstrapper] Loading System.Runtime.InteropServices
> [ 01:38:42.4640414 | SPL ] [Bootstrapper] Loading System.Collections
> [ 01:38:42.4641924 | SPL ] [Bootstrapper] Loading System.Linq
> [ 01:38:42.4695618 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.4832920 | SPL ] [Bootstrapper] Loading Iced
> [ 01:38:42.4921869 | SPL ] [Bootstrapper] Loading netstandard
> [ 01:38:42.5273448 | SPL ] [Bootstrapper] Loading System.Memory
> [ 01:38:42.5287236 | SPL ] [Bootstrapper] Loading System.Collections.NonGeneric
> [ 01:38:42.5542923 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.5551931 | SPL ] [Bootstrapper] Loading System.Linq
> [ 01:38:42.5582851 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.5583389 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.5583690 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.5584027 | SPL ] [kernel32.dll] Resolved Path: 
> [ 01:38:42.5974489 | SPL ] [Matchmaking] Found SteamMatchmaking interface getter at 0x143E98558
> [ 01:38:42.5975323 | SPL ] [Preloader] Initialized
> [ 01:38:42.5982110 | SPL ] [Bootstrapper] Loading System.IO.FileSystem.Watcher
> [ 01:38:42.6065516 | SPL ] [Bootstrapper] Loading System.Reflection.Metadata
> [ 01:38:42.6096084 | SPL ] [Bootstrapper] Loading System.Threading.Thread
> [ 01:38:42.6142340 | SPL ] [Bootstrapper] Loading System.Runtime.Loader
> [ 01:38:42.6144335 | SPL ] [Bootstrapper] Loading System.Threading
> [ 01:38:42.6171279 | SPL ] Attempting to load nativePC/plugins/CSharp\BetterMatchmaking\BetterMatchmaking.dll
> [ 01:38:42.6177470 | SPL ] Creating ALC for assembly BetterMatchmaking
> [ 01:38:42.6195981 | SPL ] [BetterMatchmaking, Culture=neutral, PublicKeyToken=null] Resolved Path: C:\Program Files (x86)\Steam\steamapps\common\Monster Hunter World\nativePC\plugins\CSharp\BetterMatchmaking\BetterMatchmaking.dll
> [ 01:38:42.6229636 | SPL ] [System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] Resolved Path: 
> [ 01:38:42.6230695 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:38:42.6237101 | SPL ] [SharpPluginLoader.Core, Version=0.0.4.1, Culture=neutral, PublicKeyToken=null] Resolved Path: 
> [ 01:38:42.6237997 | SPL ] [System.Numerics.Vectors, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] Resolved Path: 
> [ 01:38:42.6238188 | SPL ] [Bootstrapper] Loading System.Numerics.Vectors
> [ 01:38:42.6246398 | SPL ] Loading plugin BetterMatchmaking
> [ 01:38:42.6273118 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnPreMain
> [ 01:38:42.6273712 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnWinMain
> [ 01:38:42.6273981 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnUpdate
> [ 01:38:42.6274117 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnSave
> [ 01:38:42.6274221 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnSelectSaveSlot
> [ 01:38:42.6274316 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnResourceLoad
> [ 01:38:42.6274426 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnChatMessageSent
> [ 01:38:42.6274513 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestAccept
> [ 01:38:42.6274629 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestCancel
> [ 01:38:42.6274717 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestDepart
> [ 01:38:42.6274805 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestEnter
> [ 01:38:42.6274892 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestLeave
> [ 01:38:42.6274977 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestComplete
> [ 01:38:42.6275063 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestFail
> [ 01:38:42.6275155 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestReturn
> [ 01:38:42.6275238 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnQuestAbandon
> [ 01:38:42.6275321 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterCreate
> [ 01:38:42.6275409 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterInitialized
> [ 01:38:42.6275499 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterAction
> [ 01:38:42.6275582 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterFlinch
> [ 01:38:42.6275663 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterEnrage
> [ 01:38:42.6275746 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterUnenrage
> [ 01:38:42.6275847 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterDeath
> [ 01:38:42.6275944 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnMonsterDestroy
> [ 01:38:42.6276034 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnPlayerAction
> [ 01:38:42.6276114 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnWeaponChange
> [ 01:38:42.6276197 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnEntityAction
> [ 01:38:42.6276281 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnEntityAnimation
> [ 01:38:42.6276364 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnEntityAnimationUpdate
> [ 01:38:42.6276455 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnSendPacket
> [ 01:38:42.6276571 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnReceivePacket
> [ 01:38:42.6276671 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnLobbySearch
> [ 01:38:42.6276756 | SPL ] Plugin Better Matchmaking v2.0 does not implement OnRender
> [ 01:38:42.6276847 | SPL ] Plugin Better Matchmaking v2.0 implements OnImGuiRender
> [ 01:38:42.6276935 | SPL ] Plugin Better Matchmaking v2.0 implements OnImGuiFreeRender
> [ 01:38:50.0835756 | SPL ] [Better Matchmaking] Managers: Initializing...
> [ 01:38:50.0841750 | SPL ] [System.Collections, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] Resolved Path: 
> [ 01:38:50.0842167 | SPL ] [Bootstrapper] Loading System.Collections
> [ 01:38:50.0854857 | SPL ] [Better Matchmaking] LocalizationManager: Initializing...
> [ 01:38:50.0858282 | SPL ] [System.IO.FileSystem.Watcher, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] Resolved Path: 
> [ 01:38:50.0858601 | SPL ] [Bootstrapper] Loading System.IO.FileSystem.Watcher
> [ 01:38:50.0868589 | SPL ] [Better Matchmaking] Localization en-us: Initializing...
> [ 01:38:50.0897844 | SPL ] [Better Matchmaking] Localization en-us: Done!
> [ 01:38:50.0898922 | SPL ] [Better Matchmaking] Localization en-us: Saving...
> [ 01:38:50.0899899 | SPL ] [Better Matchmaking] LocalizationChangeWatcher: Localization en-us: Temporarily Disabling...
> [ 01:38:50.0946493 | SPL ] [System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51] Resolved Path: 
> [ 01:38:50.0947044 | SPL ] [Bootstrapper] Loading System.Text.Json
> [ 01:38:50.0948792 | SPL ] [System.Text.Encodings.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51] Resolved Path: 
> [ 01:38:50.0949047 | SPL ] [Bootstrapper] Loading System.Text.Encodings.Web
> [ 01:38:50.1161659 | SPL ] [Better Matchmaking] LocalizationManager: Loading All Localizations...
> [ 01:38:50.1167465 | SPL ] [Better Matchmaking] LocalizationManager: Loading All Localizations Done!
> [ 01:38:50.1169088 | SPL ] [Better Matchmaking] LocalizationChangeWatcher: Initializing...
> [ 01:38:50.1171580 | SPL ] [Better Matchmaking] LocalizationChangeWatcher: Initialization Done!
> [ 01:38:50.1171743 | SPL ] [Better Matchmaking] LocalizationManager: Initialization Done!
> [ 01:38:50.1173395 | SPL ] [Better Matchmaking] ConfigManager: Initializing...
> [ 01:38:50.1194939 | SPL ] [Better Matchmaking] Default Config: Initializing...
> [ 01:38:50.1195153 | SPL ] [Better Matchmaking] Default Config: Initialization Done!
> [ 01:38:50.1197051 | SPL ] [Better Matchmaking] Config: Loading...
> [ 01:38:50.1835013 | SPL ] [Better Matchmaking] Config: Initializing...
> [ 01:38:50.1906936 | SPL ] [Better Matchmaking] Config: Initialization Done!
> [ 01:38:50.1907272 | SPL ] [Better Matchmaking] Config: Loading Done!
> [ 01:38:50.1915149 | SPL ] [Better Matchmaking] Config: Saving...
> [ 01:38:50.1915859 | SPL ] [Better Matchmaking] ConfigChangeWatcher: Temporarily Disabling...
> [ 01:38:50.2134409 | SPL ] [Better Matchmaking] Config: Saving Done!
> [ 01:38:50.2136089 | SPL ] [Better Matchmaking] ConfigChangeWatcher: Initializing...
> [ 01:38:50.2137872 | SPL ] [Better Matchmaking] ConfigChangeWatcher: Initialization Done!
> [ 01:38:50.2138042 | SPL ] [Better Matchmaking] ConfigManager: Initialization Done!
> [ 01:38:50.2142154 | SPL ] [Better Matchmaking] Core: Initializing...
> [ 01:38:50.2153261 | SPL ] [steam_api64.dll] Resolved Path: 
> [ 01:38:50.2540845 | SPL ] [Matchmaking: Found SteamMatchmaking interface getter at 0x143E98558
> [ 01:38:50.2546715 | SPL ] [steam_api64.dll] Resolved Path: 
> [ 01:38:50.2547657 | SPL ] [Better Matchmaking] Core: Initialization Done!
> [ 01:38:50.2548077 | SPL ] [Better Matchmaking] Managers: Initialization Done!
> [ 01:39:02.0752596 | SPL ] [Better Matchmaking] [OnNumericalFilter] steamInterface: 60361488, keyAddress: 4, comparison: ==, value: 0
> [ 01:39:05.5893213 | SPL ] Found GetMonsterDti function at 0x14139EAF0
> [ 01:39:05.5893809 | SPL ] Found EmDtiTable at 0x143EEFC60
> [ 01:39:07.2830157 | SPL ] Found cD3DRender::isD3D12 at 0x1424e8250
> [ 01:39:07.2850550 | SPL ] Initializing D3D module for D3D12
> [ 01:39:07.3081306 | SPL ] Found D3D12 command queue
> [ 01:39:07.3083342 | SPL ] [Bootstrapper] Loading ImGui.NET
> [ 01:39:07.3120374 | SPL ] [Bootstrapper] Loading System.Runtime
> [ 01:39:07.3139482 | SPL ] [Bootstrapper] Loading System.Numerics.Vectors
> [ 01:39:07.3150879 | SPL ] Initializing Renderer with
> 
>     Viewport Size: 2560x1600
> 
>     Window Size: 2560x1600
> [ 01:39:07.3151180 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.3374173 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.3379423 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.3409299 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.3424502 | SPL ] Renderer.Initialize
> [ 01:39:07.3424766 | SPL ] Loading cimgui.dll
> [ 01:39:07.4769471 | SPL ] Creating RTV for back buffer 0, with size 2560x1600
> [ 01:39:07.4769889 | SPL ] Creating RTV for back buffer 1, with size 2560x1600
> [ 01:39:07.4769982 | SPL ] Creating RTV for back buffer 2, with size 2560x1600
> [ 01:39:07.5108069 | SPL ] Initialized D3D12
> [ 01:39:07.5108702 | SPL ] [PrimitiveRenderingModule] Late init
> [ 01:39:07.5323551 | SPL ] [PrimitiveRenderingModule] Creating frame contexts
> [ 01:39:07.5346866 | SPL ] [Bootstrapper] Loading System.Reflection.Emit.Lightweight
> [ 01:39:07.5348106 | SPL ] [Bootstrapper] Loading System.Reflection.Emit.ILGeneration
> [ 01:39:07.5348518 | SPL ] [Bootstrapper] Loading System.Reflection.Primitives
> [ 01:39:07.5394340 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5401238 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5405715 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5413994 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5418485 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5422482 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5426637 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:07.5430586 | SPL ] [cimgui] Resolved Path: nativePC/plugins/CSharp/Loader/cimgui.dll
> [ 01:39:27.6501609 | SPL ] [Better Matchmaking] [OnStartRequest] phase: 0, netCore: 5197747568, netRequest: 5197850272
> [ 01:39:27.6505563 | SPL ] [Better Matchmaking] 1
> [ 01:39:27.6505954 | SPL ] [Better Matchmaking] 2

**Comment by GreenComfyTea** [comment]
Potentially fixed in ca765942d6dd1f88ed020df3dd2282816b38d697. Released with https://github.com/GreenComfyTea/MHW-Better-Matchmaking/releases/tag/v2.1. Will close later if I don't receive reports that the fix is not working.
