### ISSUE TITLE
A traditional Chinese translation for your MOD

### ISSUE THREAD

**Issue by Alpha-Cyg** [GreenComfyTea/MHW-Better-Matchmaking#3]
Hope it can be helpful
[zh-cht.json](https://github.com/GreenComfyTea/MHW-Better-Matchmaking/files/14766637/zh-cht.json)

**Comment by GreenComfyTea** [comment]
`zh-cht` is considered legacy in .NET world (see [this](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.threeletterisolanguagename?view=net-8.0)). I will take the liberty of renaming it to `zh-hant`.

**Comment by GreenComfyTea** [comment]
I am about to add custom font support. I haven't pushed any changes yet but you can start thinking what font you want your translation to have.
