### ISSUE TITLE
Returning to title screen crashes game

### ISSUE THREAD

**Issue by Fiddydamage** [GreenComfyTea/MHW-Better-Matchmaking#7]
With better matchmaking installed and working, selecting the "return to title screen" option (and saying yes to save) causes the game to close/crash with no error message.

currently using version 2.3 of better matchmaking with sharpplugingloader v 0.0.6.1 (unrelated: the install instructions on the main github page say to use pluginloader 0.0.6 still )

**Comment by GreenComfyTea** [comment]
This is an issue with SharpPluginLoader that has been already fixed. The fix will be included in v0.7.0.0 release. For now you can use one the builds provided by me: [link](https://github.com/GreenComfyTea/MHW-Better-Matchmaking/releases/tag/SPL-v0.0.6.1-ea62641). This has been explained in a sticky post on nexus.
